- name: Instalando pacotes para provisionar ambiente Wordpress
  hosts: all
  tasks:
    - name: instalando pacotes
      become: true
      apt:
        name: "{{item}}"
      loop:
        - apache2
        - php5
        - libapache2-mod-php5
        - php5-gd
        - libssh2-php
        - php5-mcrypt
        - mysql-server-5.6
        - python-mysqldb
        - php5-mysql
        -
    - name: 'Cria o banco do MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present