- name: Instalando serviços para provisionar o php com apache
  hosts: all
  tasks:
    - name: instalando pacotes
      become: true
      apt:
        name: "{{item}}"
      loop:
        - apache2
        - php5
        - libapache2-mod-php5

